marks = ['Outstanding', 'Good', 'Unsatisfactory', 'Good', 'Poor']
marks.count('Poor')
marks.count('Good')
marks.index('Good')
marks.index('Good', 2)
marks.reverse()
print(marks)
marks.append('Satisfactory')
print(marks)
marks.sort()
print(marks)
marks.pop()
marks.pop(2)
print(marks)
